version: '2'
services:
  activemq-test: 
    build:          #镜像构建
      context:  .   #构建镜像时所在的资源路径
      dockerfile: Dockerfile    #构建镜像时需要的dockerfile文件路径
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"
    image: activemq-test:v1

  ## 最简单，无需任何配置，请使用这个下面配置 来启动容器
  # version: '2'
  #   services:
  #     activemq-test: 
  #       ports:
  #         - "8161:8161"
  #         - "61616:61616"
  #         - "5672:5672"
  #         - "61613:61613"
  #         - "1883:1883"
  #         - "61614:61614"
  #       image:  webcenter/activemq:latest
    
    